# Generated by Django 2.2.3 on 2019-07-06 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('college', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=32)),
                ('classinfo', models.CharField(max_length=32)),
                ('photo', models.ImageField(default='upload_imag/default.png', upload_to='upload_imag/')),
                ('signature', models.CharField(default='Hello World!', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(blank=True, max_length=256)),
                ('category', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('view_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('publish_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.userinfo')),
            ],
        ),
    ]
