# Generated by Django 2.2.3 on 2019-07-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20190707_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=16)),
                ('posts', models.ManyToManyField(to='main_page.post')),
            ],
        ),
        migrations.CreateModel(
            name='post_like_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_page.post')),
            ],
        ),
        migrations.CreateModel(
            name='post_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True)),
                ('like_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_page.userinfo')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_page.post')),
            ],
        ),
    ]
